version: '3.1'
services:
  portainer:
    image: portainer/portainer:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
#      - ./data/portainer/data:/data
    ports:
      - 9000:9000